INSERT INTO `questions` (`id`,`answer_a`,`answer_b`,`answer_c`,`answer_d`,`answer_e`,`answer_f`,`answer_g`,`answer_h`,`answer_i`,`answer_j`,`answer_permutation`,`content`,`group_id`,`question_type`,`right_answer`,`suggest`,`user_id`) VALUES (1,'locate','displace','establish','put up',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ONE_ANSWER',NULL,NULL,4);
INSERT INTO `questions` (`id`,`answer_a`,`answer_b`,`answer_c`,`answer_d`,`answer_e`,`answer_f`,`answer_g`,`answer_h`,`answer_i`,`answer_j`,`answer_permutation`,`content`,`group_id`,`question_type`,`right_answer`,`suggest`,`user_id`) VALUES (2,'Bill said that he had never been to Russia and he thought he would go there the next year.','Bill said that he would have never been to Russia and he thinks he would go there the next year.','Bill said that he had never been to Russia and he thinks he will go there the next year.','Bill said that he has never been to Russia and he thinks he would go there the next year.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'<div class="answer-result">
	<p>Đáp án A</p>
	<p>Câu ban đầu: Bill nói “Tôi chưa đến nước Nga bao giờ. Tôi nghĩ tôi sẽ đến đó vào năm tới.”</p>
	<p>Đáp án B, C, D đều sai về mặt ngữ pháp vì khong lùi thì động từ “think” khi chuyển từ câu trực tiếp sang gián tiếp.</p>
</div>',NULL,'ONE_ANSWER','A','<div class="answer-result">
	<p>Đáp án A</p>
	<p>Câu ban đầu: Bill nói “Tôi chưa đến nước Nga bao giờ. Tôi nghĩ tôi sẽ đến đó vào năm tới.”</p>
	<p>Đáp án B, C, D đều sai về mặt ngữ pháp vì khong lùi thì động từ “think” khi chuyển từ câu trực tiếp sang gián tiếp.</p>
</div>',4);
INSERT INTO `questions` (`id`,`answer_a`,`answer_b`,`answer_c`,`answer_d`,`answer_e`,`answer_f`,`answer_g`,`answer_h`,`answer_i`,`answer_j`,`answer_permutation`,`content`,`group_id`,`question_type`,`right_answer`,`suggest`,`user_id`) VALUES (3,'Jane is believed to have retired because of her poor health.','Jane was believed to have retired because of her poor health.','It is believed that Jane retired because of her poor health.','Jane retired because of her poor health was believed.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ONE_ANSWER','B',NULL,4);
INSERT INTO `questions` (`id`,`answer_a`,`answer_b`,`answer_c`,`answer_d`,`answer_e`,`answer_f`,`answer_g`,`answer_h`,`answer_i`,`answer_j`,`answer_permutation`,`content`,`group_id`,`question_type`,`right_answer`,`suggest`,`user_id`) VALUES (4,'The government knows the extent of the problem whereas it needs to take action soon.','The government knows the extent of the problem so that it needs to take action soon.','The government knows the extent of the problem so that it needs to take action soon.','The government knows the extent of the problem so that it needs to take action soon.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ONE_ANSWER','C',NULL,4);
INSERT INTO `questions` (`id`,`answer_a`,`answer_b`,`answer_c`,`answer_d`,`answer_e`,`answer_f`,`answer_g`,`answer_h`,`answer_i`,`answer_j`,`answer_permutation`,`content`,`group_id`,`question_type`,`right_answer`,`suggest`,`user_id`) VALUES (5,'Since the substance is very toxic, so protective clothing must be worn at all times.','So toxic is the substance that protective clothing must be worn at all times.','The substance is such toxic that protective clothing must be worn at all times.','The substance is too toxic to wear protective clothing at all times.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ONE_ANSWER','B',NULL,4);
